# -*- coding: utf-8 -*-
"""RBC-CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_18GmKe-Cfgm_elFFDdfGHxlGrC5fXra
"""

import os
import shutil
from sklearn.model_selection import train_test_split

# Install patool to extract .rar files
!pip install patool
import patoolib

# Define paths
rar_path = '/content/RBC.rar'
extract_path = '/content/extracted_images'

# Create extraction directory
if not os.path.exists(extract_path):
    os.makedirs(extract_path)

# Extract the RAR file
patoolib.extract_archive(rar_path, outdir=extract_path)

import os

# Path where the RAR was extracted
extract_path = '/content/extracted_images'
rbc_path = os.path.join(extract_path, 'RBC')

# Identify classes (subdirectories)
path_to_check = rbc_path if os.path.exists(rbc_path) else extract_path
classes = [d for d in os.listdir(path_to_check) if os.path.isdir(os.path.join(path_to_check, d))]

print(f"Found {len(classes)} classes in {path_to_check}:")
for cls in sorted(classes):
    print(f" - {cls}")

# List the actual classes found inside the split directories
classes_dir = os.path.join(path_to_check, 'train')
if os.path.exists(classes_dir):
    actual_classes = [d for d in os.listdir(classes_dir) if os.path.isdir(os.path.join(classes_dir, d))]
    print(f"Class types found in the dataset:")
    for c in sorted(actual_classes):
        print(f" - {c}")
else:
    print("Could not find a 'train' directory to list classes from.")

"""### Clinical Significance of Class Labels
The labels in this dataset correspond to specific Red Blood Cell (RBC) morphologies that are clinical indicators for various conditions:

1.  **Normal**: Healthy, biconcave disc-shaped RBCs.
2.  **Acanthocyte**: Spiky cells often associated with liver disease or abetalipoproteinemia.
3.  **Burr cell (Echinocyte)**: Cells with small, regular projections; often seen in kidney disease (uremia) or dehydration.
4.  **Hypochromia**: Pale cells with less hemoglobin, typically indicating Iron Deficiency Anemia.
5.  **Ovalocyte / Elliptocyte**: Oval-shaped cells seen in Hereditary Elliptocytosis or various anemias.
6.  **Schistocyte**: Fragmented cells indicating mechanical damage, often seen in Microangiopathic Hemolytic Anemia (MAHA).
7.  **Spherocyte**: Sphere-shaped cells seen in Hereditary Spherocytosis or Immune Hemolytic Anemia.
8.  **Stomatocyte**: Cells with a mouth-like central pallor, associated with hereditary conditions or alcoholism.
9.  **Target Cell (Codocyte)**: Resembling a bullseye; common in Thalassemia, liver disease, or post-splenectomy.
10. **Cigar cell**: A subtype of elliptocyte, often associated with severe Iron Deficiency Anemia.
11. **Teardrop (Dacrocyte)**: Shaped like a drop, frequently seen in Myelofibrosis or bone marrow disorders.
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import math

# We'll look into the train folder for samples
samples_dir = os.path.join(path_to_check, 'train')
classes = sorted([d for d in os.listdir(samples_dir) if os.path.isdir(os.path.join(samples_dir, d))])

# Setup the grid
cols = 3
rows = math.ceil(len(classes) / cols)
fig, axes = plt.subplots(rows, cols, figsize=(15, rows * 4))
axes = axes.flatten()

for i, cls in enumerate(classes):
    cls_path = os.path.join(samples_dir, cls)
    img_files = [f for f in os.listdir(cls_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    if img_files:
        img_path = os.path.join(cls_path, img_files[0])
        img = mpimg.imread(img_path)
        axes[i].imshow(img)
        axes[i].set_title(f"Type: {cls}")
        axes[i].axis('off')
    else:
        axes[i].text(0.5, 0.5, f"No images in {cls}", ha='center')
        axes[i].axis('off')

# Hide unused axes
for j in range(i + 1, len(axes)):
    axes[j].axis('off')

plt.tight_layout()
plt.show()

"""### 1. Data Preparation
We will use `tf.keras.utils.image_dataset_from_directory` to load the images. We'll set a standard image size (e.g., 128x128) and batch size.
"""

import tensorflow as tf

IMG_SIZE = (128, 128)
BATCH_SIZE = 32

# Define directory paths based on the previous extraction
train_path = '/content/extracted_images/RBC/train'
val_path = '/content/extracted_images/RBC/val'
test_path = '/content/extracted_images/RBC/test'

# Load datasets
train_ds = tf.keras.utils.image_dataset_from_directory(
    train_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    val_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

class_names = train_ds.class_names
print(f"Loaded classes: {class_names}")

"""### 2. Model Definition
Now, we'll define a simple Convolutional Neural Network (CNN). We include a rescaling layer to normalize pixel values between 0 and 1.
"""

from tensorflow.keras import layers, models

num_classes = len(class_names)

model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(128, 128, 3)),
    layers.Conv2D(32, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(128, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

EPOCHS = 10
STEPS_PER_EPOCH = 200

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    steps_per_epoch=STEPS_PER_EPOCH
)

# Visualize results
import matplotlib.pyplot as plt

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.legend()
plt.title('Accuracy')

plt.subplot(1, 2, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.legend()
plt.title('Loss')
plt.show()

"""### 4. Model Evaluation
Now that the model is trained, let's evaluate its performance using the test dataset that was not used during training or validation.
"""

test_loss, test_acc = model.evaluate(test_ds)
print(f'\nTest accuracy: {test_acc:.4f}')
print(f'Test loss: {test_loss:.4f}')

"""### 5. Visualizing Real vs Predicted Labels
Let's take a sample batch from the test set and compare the model's predictions with the actual ground truth.
"""

import numpy as np

# Retrieve a single batch of images and labels from the test set
image_batch, label_batch = next(iter(test_ds))

# Generate predictions
predictions = model.predict(image_batch)
pred_labels = np.argmax(predictions, axis=1)
true_labels = np.argmax(label_batch, axis=1)

# Plot the results
plt.figure(figsize=(15, 10))
for i in range(9): # Display first 9 images
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image_batch[i].numpy().astype("uint8"))

    actual_name = class_names[true_labels[i]]
    predicted_name = class_names[pred_labels[i]]

    # Color green if correct, red if incorrect
    color = 'green' if actual_name == predicted_name else 'red'

    plt.title(f"Real: {actual_name}\nPred: {predicted_name}", color=color)
    plt.axis("off")

plt.tight_layout()
plt.show()

"""### 6. Transfer Learning with ResNet50
We will use a pre-trained ResNet50 model as a feature extractor and train it on our RBC dataset.
"""

from tensorflow.keras.applications import ResNet50

# Base model with pre-trained weights
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(128, 128, 3))
base_model.trainable = False  # Freeze the base model layers

# Create the new model
resnet_model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(128, 128, 3)),
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(num_classes, activation='softmax')
])

resnet_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

resnet_model.summary()

RESNET_EPOCHS = 10
RESNET_STEPS = 200

history_resnet = resnet_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=RESNET_EPOCHS,
    steps_per_epoch=RESNET_STEPS
)

# Evaluate ResNet on test set
resnet_test_loss, resnet_test_acc = resnet_model.evaluate(test_ds)
print(f'\nResNet Test accuracy: {resnet_test_acc:.4f}')

"""### 7. ResNet50: Real vs Predicted
Let's visualize the results for the ResNet50 model on a sample batch from the test set.
"""

import numpy as np
import matplotlib.pyplot as plt

# Get a batch from test_ds
image_batch, label_batch = next(iter(test_ds))

# Predict using ResNet
resnet_predictions = resnet_model.predict(image_batch)
resnet_pred_labels = np.argmax(resnet_predictions, axis=1)
true_labels = np.argmax(label_batch, axis=1)

plt.figure(figsize=(15, 10))
for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image_batch[i].numpy().astype("uint8"))

    actual_name = class_names[true_labels[i]]
    predicted_name = class_names[resnet_pred_labels[i]]

    color = 'green' if actual_name == predicted_name else 'red'

    plt.title(f"Real: {actual_name}\nResNet Pred: {predicted_name}", color=color)
    plt.axis("off")

plt.tight_layout()
plt.show()

"""### 7. ResNet50: Real vs Predicted
Let's visualize the results for the ResNet50 model.
"""

import numpy as np
import matplotlib.pyplot as plt

# Get a batch from test_ds
image_batch, label_batch = next(iter(test_ds))

# Predict using ResNet
resnet_predictions = resnet_model.predict(image_batch)
resnet_pred_labels = np.argmax(resnet_predictions, axis=1)
true_labels = np.argmax(label_batch, axis=1)

plt.figure(figsize=(15, 10))
for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image_batch[i].numpy().astype("uint8"))

    actual_name = class_names[true_labels[i]]
    predicted_name = class_names[resnet_pred_labels[i]]

    color = 'green' if actual_name == predicted_name else 'red'

    plt.title(f"Real: {actual_name}\nResNet Pred: {predicted_name}", color=color)
    plt.axis("off")

plt.tight_layout()
plt.show()

"""### 8. Saving Models and Dataset
We will save the models to the local environment and create a zip archive of the extracted images.
"""

# Save the models
model.save('rbc_cnn_model.keras')
resnet_model.save('rbc_resnet_model.keras')

print("Models saved as 'rbc_cnn_model.keras' and 'rbc_resnet_model.keras'")

# Zip the extracted dataset
import shutil
# The directory we want to zip is /content/extracted_images/RBC
shutil.make_archive('rbc_dataset_backup', 'zip', '/content/extracted_images/RBC')

print("Dataset compressed into 'rbc_dataset_backup.zip'")

"""### 13. Image Enhancement and Retraining
We will define a preprocessing function to apply CLAHE enhancement to the images and then retrain our CNN model to see if performance improves.
"""

import cv2
import numpy as np
import tensorflow as tf

def enhance_image(image):
    # image is a single image tensor from the batch
    img_np = image.numpy().astype(np.uint8)

    # Handle grayscale images by converting to RGB first
    if len(img_np.shape) == 2 or img_np.shape[2] == 1:
        img_np = cv2.cvtColor(img_np, cv2.COLOR_GRAY2RGB)
    elif img_np.shape[2] == 4:
        img_np = cv2.cvtColor(img_np, cv2.COLOR_RGBA2RGB)

    # Convert to LAB to apply CLAHE on the Luminance channel
    lab = cv2.cvtColor(img_np, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)

    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
    cl = clahe.apply(l)

    limg = cv2.merge((cl,a,b))
    enhanced = cv2.cvtColor(limg, cv2.COLOR_LAB2RGB)
    return enhanced.astype(np.float32)

# Helper to apply the py_function to a batch
def process_batch(images, labels):
    enhanced_images = tf.map_fn(lambda img: tf.py_function(enhance_image, [img], tf.float32), images, dtype=tf.float32)
    return enhanced_images, labels

# Map enhancement to datasets
train_ds_enhanced = train_ds.map(process_batch)
val_ds_enhanced = val_ds.map(process_batch)
test_ds_enhanced = test_ds.map(process_batch)

# Ensure shapes are correctly set for Keras
def set_shapes(img, label):
    img.set_shape((None, 128, 128, 3))
    label.set_shape((None, 11))
    return img, label

train_ds_enhanced = train_ds_enhanced.map(set_shapes)
val_ds_enhanced = val_ds_enhanced.map(set_shapes)
test_ds_enhanced = test_ds_enhanced.map(set_shapes)

# Re-initialize and train the CNN model with enhanced data
model_enhanced = models.clone_model(model)
model_enhanced.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("Starting training on enhanced images...")
history_enhanced = model_enhanced.fit(
    train_ds_enhanced,
    validation_data=val_ds_enhanced,
    epochs=10,
    steps_per_epoch=200
)

# Final evaluation
final_loss, final_acc = model_enhanced.evaluate(test_ds_enhanced)
print(f'\nEnhanced Test accuracy: {final_acc:.4f}')

"""### 14. Comparative Analysis: Pre vs. Post Enhancement
We compare the training metrics and final test accuracy of the baseline CNN against the CNN trained on CLAHE-enhanced images.
"""

import matplotlib.pyplot as plt

# Plotting Accuracy Comparison
plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['val_accuracy'], label='Original Validation Acc', linestyle='--')
plt.plot(history_enhanced.history['val_accuracy'], label='Enhanced Validation Acc', linewidth=2)
plt.title('Validation Accuracy Comparison')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

# Plotting Loss Comparison
plt.subplot(1, 2, 2)
plt.plot(history.history['val_loss'], label='Original Validation Loss', linestyle='--')
plt.plot(history_enhanced.history['val_loss'], label='Enhanced Validation Loss', linewidth=2)
plt.title('Validation Loss Comparison')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# Summary Table
comparison_data = {
    'Metric': ['Test Accuracy', 'Test Loss'],
    'Original Model': [f"{test_acc:.4f}", f"{test_loss:.4f}"],
    'Enhanced Model': [f"{final_acc:.4f}", f"{final_loss:.4f}"]
}
import pandas as pd
display(pd.DataFrame(comparison_data))

"""### 10. Morphological Analysis
In this section, we take one representative image from each of the 11 classes and perform morphological operations to highlight their structural differences.
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Prepare the classes and find one sample image per class
samples_dir = '/content/extracted_images/RBC/train'
classes = sorted([d for d in os.listdir(samples_dir) if os.path.isdir(os.path.join(samples_dir, d))])

fig, axes = plt.subplots(len(classes), 3, figsize=(12, len(classes) * 3))
plt.subplots_adjust(hspace=0.4)

for i, cls in enumerate(classes):
    cls_path = os.path.join(samples_dir, cls)
    img_name = os.listdir(cls_path)[0]
    img_path = os.path.join(cls_path, img_name)

    # 1. Load Original
    img = cv2.imread(img_path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 2. Pre-processing for Morphology
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Apply Gaussian blur to reduce noise
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    # Global thresholding (Otsu's method)
    _, thresh = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    # 3. Morphological Operations (Closing to fill small holes)
    kernel = np.ones((5, 5), np.uint8)
    morph = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)

    # Plotting
    axes[i, 0].imshow(img_rgb)
    axes[i, 0].set_title(f"{cls}: Original")
    axes[i, 0].axis('off')

    axes[i, 1].imshow(thresh, cmap='gray')
    axes[i, 1].set_title("Otsu Threshold")
    axes[i, 1].axis('off')

    axes[i, 2].imshow(morph, cmap='gray')
    axes[i, 2].set_title("Morphological Closing")
    axes[i, 2].axis('off')

plt.show()

"""### 15. Additional Enhancement: Multi-Scale Retinex (MSR)
Retinex enhancement aims to improve the dynamic range of the image by estimating the lighting conditions. We use multiple Gaussian blurs (scales) to simulate the way the human eye perceives detail across different spatial frequencies.
"""

def single_scale_retinex(img, sigma):
    retinex = np.log10(img.astype(np.float32) + 1.0) - np.log10(cv2.GaussianBlur(img.astype(np.float32), (0, 0), sigma) + 1.0)
    return retinex

def multi_scale_retinex(img, sigma_list):
    retinex = np.zeros_like(img, dtype=np.float32)
    for sigma in sigma_list:
        retinex += single_scale_retinex(img, sigma)
    retinex = retinex / len(sigma_list)

    # Normalize to 0-255
    retinex = cv2.normalize(retinex, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    return retinex

# Visualize MSR on samples
fig, axes = plt.subplots(len(classes), 2, figsize=(8, len(classes) * 3))

for i, cls in enumerate(classes):
    cls_path = os.path.join(samples_dir, cls)
    img_name = os.listdir(cls_path)[0]
    img_path = os.path.join(cls_path, img_name)
    img = cv2.imread(img_path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Apply MSR with 3 scales
    msr_img = np.zeros_like(img_rgb)
    for channel in range(3):
        msr_img[:,:,channel] = multi_scale_retinex(img_rgb[:,:,channel], [15, 80, 250])

    axes[i, 0].imshow(img_rgb)
    axes[i, 0].set_title(f"{cls}: Original")
    axes[i, 0].axis('off')

    axes[i, 1].imshow(msr_img)
    axes[i, 1].set_title("Multi-Scale Retinex")
    axes[i, 1].axis('off')

plt.tight_layout()
plt.show()

# Compare results in a table
comparison_results = {
    'Model Version': ['Original (10 ep)', 'CLAHE Enhanced (10 ep)', 'MSR Enhanced (3 ep)'],
    'Test Accuracy': [f"{test_acc:.4f}", f"{final_acc:.4f}", f"{msr_acc:.4f}"]
}
display(pd.DataFrame(comparison_results))



import pandas as pd

stats_list = []

for cls in classes:
    cls_path = os.path.join(samples_dir, cls)
    img_name = os.listdir(cls_path)[0]
    img_path = os.path.join(cls_path, img_name)

    # Re-run thresholding and closing to get the mask
    img = cv2.imread(img_path, 0)
    blurred = cv2.GaussianBlur(img, (5, 5), 0)
    _, thresh = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    mask = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8))

    # Find contours
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:
        # Assume the largest contour is the cell
        cnt = max(contours, key=cv2.contourArea)
        area = cv2.contourArea(cnt)
        perimeter = cv2.arcLength(cnt, True)

        # Circularity = 4 * pi * Area / (Perimeter^2)
        circularity = (4 * np.pi * area) / (perimeter**2) if perimeter > 0 else 0

        stats_list.append({
            'Class': cls,
            'Area': area,
            'Perimeter': round(perimeter, 2),
            'Circularity': round(circularity, 3)
        })

df_morph = pd.DataFrame(stats_list)
print("Morphological Characteristics per Class:")
display(df_morph)

